# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-02 13:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontakty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('street_number', models.IntegerField()),
                ('local_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_adress', models.CharField(max_length=64)),
                ('email_type', models.IntegerField(choices=[(0, 'niezdefiniowany'), (1, 'domowy'), (2, 'sluzbowy')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('phone_type', models.IntegerField(choices=[(0, 'niezdefiniowany'), (1, 'domowy'), (2, 'komorkowy'), (3, 'sluzbowy')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='phone',
            name='phone_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kontakty.Person'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_member',
            field=models.ManyToManyField(null=True, to='kontakty.Person'),
        ),
        migrations.AddField(
            model_name='email',
            name='email_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kontakty.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kontakty.Adress'),
        ),
    ]
